name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Add .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TEST_USER_FILEROOMID: ${{ secrets.TEST_USER_FILEROOMID }}
          envkey_TEST_USER_DARTROOMID: ${{ secrets.TEST_USER_DARTROOMID }}
          envkey_TEST_USER_DARTROOM_TOKEN: ${{ secrets.TEST_USER_DARTROOM_TOKEN }}
          envkey_TEST_USER_FILEROOM_TOKEN: ${{ secrets.TEST_USER_FILEROOM_TOKEN }}
          envkey_TEST_DEV_USERNAME: ${{ secrets.TEST_DEV_USERNAME }}
          envkey_TEST_DEV_PASSWORD: ${{ secrets.TEST_DEV_PASSWORD }}
          env_key_TEST_DEV_API_KEY: ${{ secrets.TEST_DEV_API_KEY }}
          env_key_FILEROOM_ENV: ${{ secrets.FILEROOM_ENV }}
          env_key_TEST_FILECID: ${{ secrets.TEST_FILECID }}

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
