name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build --if-present
      - name: Add .env file
        run: |
          echo "${{ secrets.TEST_USER_DARTROOMID }}" > .env
          echo "${{ secrets.TEST_USER_FILEROOMID }}" >> .env
          echo "${{ secrets.TEST_USER_DARTROOM_TOKEN }}" >> .env
          echo "${{ secrets.TEST_USER_FILEROOM_TOKEN }}" >> .env
          echo "${{ secrets.TEST_DEV_USERNAME }}" >> .env
          echo "${{ secrets.TEST_DEV_PASSWORD }}" >> .env
          echo "${{ secrets.TEST_DEV_API_KEY }}" >> .env
          echo "${{ secrets.FILEROOM_ENV }}" >> .env
          echo "${{ secrets.TEST_FILECID }}" >> .env

      - name: Run tests
        run: npm  test
