name: Publish

on:
  push:
    tags:
      - v*
jobs:
  job1:
    name: fetch tag and update Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Update version
        uses: deef0000dragon1/json-edit-action@v1
        env:
          KEY: version
          VALUE: ${{ steps.tag.outputs.tag }}
          FILE: package.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update version to ${{ steps.tag.outputs.tag }}
          default_author: github_actions
          push: true

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      # Publish to the NPM registry
  job2:
    needs: job1
    name: Publishing to Repositories(NPM & GitHub Packages)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Publish to NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dartroom'

      - run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dartroom'

      - run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
